---
"extends":
  - "eslint:recommended"
"env":
  "node": true
  "mocha": true
  "es6": true
"parser": "babel-eslint"
"plugins":
  - "babel"
  - "filenames"
"rules":
  "quotes":
    - 2
    - "single"
    - "allowTemplateLiterals": true
  "strict": 0
  "no-bitwise": 0
  "max-statements": 0
